### ISSUE TITLE
Links to other documents are dead

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso-org.github.io#12]
### General Summary
Whenever another document is mentioned, its link points to a `.md` file that does not exist, instead of pointing to a `.html` file.

### Steps to Reproduce
Go to https://dev.enso.org/docs/syntax/ and click on one of the links in its body.

### Expected Result
The link gets you to the subsection.

### Actual Result
Nothing happens because the link is broken.

**Comment by joenash** [comment]
Should be fixed with https://github.com/benbalter/jekyll-relative-links, trying now 


<blockquote><img src="https://avatars0.githubusercontent.com/u/282759?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/benbalter/jekyll-relative-links">benbalter/jekyll-relative-links</a></strong></div><div>A Jekyll plugin to convert relative links to markdown files to their rendered equivalents - benbalter/jekyll-relative-links</div></blockquote>

**Comment by joenash** [comment]
Fixed by https://github.com/luna/luna.github.io/commit/f4aef3c29ea1624d0dd6d89190adcc8c2a6ad3b7
